# Generated by Django 5.0.3 on 2024-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
