# Generated by Django 5.0.3 on 2024-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_formularz_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
