# Generated by Django 4.2.11 on 2024-03-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_alter_formularz_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularz',
            old_name='message',
            new_name='dodatkowe',
        ),
    ]
